name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run HTML Validation Test
        run: npm test

      - name: Deploy to Vercel
        if: success()
        env:
          VERCEL: true
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm --prod
